config/routes.rb
Rails.application.routes.draw do
  root 'html_pages#home'
  get '/home',          to: 'html_pages#home'
  get '/about',         to: 'html_pages#about'
  get '/contact',       to: 'html_pages#contact'
  get '/cookiepolicy',  to: 'html_pages#cookiepolicy'
  get '/privacypolicy', to: 'html_pages#privacypolicy'
  get '/terms',         to: 'html_pages#terms'
  get '/blog',          to: 'blogposts#index'
  resources :blogposts, only: %i[show index]
  resources :artworks,  only: %i[show index]
  get '/paintings',     to: 'artworks#paintings'
  get '/photography',   to: 'artworks#photography'
  get '/digitalart',    to: 'artworks#digital_art'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artwork.rb
class Artwork < ApplicationRecord
  has_many_attached :images
  has_many_attached :videos

  validates :listing_name, presence: true, length: { maximum: 60 }
  validates :tags, presence: true, length: { maximum: 60 }
  validates :description, length: { maximum: 1000 }
  validates :category, presence: true, length: { maximum: 60 }
  validates :year, presence: true, numericality: { only_integer: true }
  validates :medium, length: { maximum: 60 }
  validates :height, numericality: { only_float: true, greater_than: 0, allow_blank: true }
  validates :width, numericality: { only_float: true, greater_than: 0, allow_blank: true }

  default_scope -> { order(year: :desc) }
end

app/models/blogpost.rb
class Blogpost < ApplicationRecord
  has_many_attached :images
  has_rich_text :content

  validates :post_title, presence: true, length: { maximum: 60 }

  default_scope -> { order(created_at: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  def show
    @artwork = Artwork.find(params[:id])
  end

  def index
    @artworks = Artwork.all
  end

  def paintings
    @artworks = Artwork.where('category = ?', 'Painting')
  end

  def photography
    @artworks = Artwork.where('category = ?', 'Photography')
  end

  def digital_art
    @artworks = Artwork.where('category = ?', 'Digital')
  end
end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController
  def show
    @blogpost = Blogpost.find(params[:id])
  end

  def index
    @blogposts = Blogpost.all
  end
end

app/controllers/html_pages_controller.rb
class HtmlPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def cookiepolicy
  end

  def privacypolicy
  end

  def terms
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = ' ')
    base_title = 'Lukas Hauser'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end

  def background_image(image_url)
    base_url = asset_path('thunderstruck.jpg')
    if image_url.empty?
      base_url
    else
      image_url
    end
  end
end

app/helpers/html_pages_helper.rb
module HtmlPagesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/artworks/_artwork.html.erb
<div class="col">
  <div class="card bg-transparent" style="border:none">
    <% if artwork.videos.attached? %>
      <%= link_to image_tag(artwork.videos[0], class:"card-img card-img-md"), artwork %>
    <% elsif artwork.images.attached? %>
      <%= link_to image_tag(artwork.images[0], class:"card-img card-img-md"), artwork %>
    <% end %>
    <div class="card-body">
      <p class="card-text text-center"><%= artwork.listing_name %></p>
    </div>
  </div>
</div>

app/views/artworks/_background_image.html.erb
<% if @artwork.images.attached? %>
  <%= image_tag @artwork.images[0], class:"img-fluid w-100 full-height-image" %>
<% end %>

app/views/artworks/_image_carousel.html.erb
<% if @artwork.videos.attached? %>
  <%= image_tag @artwork.videos[0], class:"img-fluid w-100 carousel-full-width-image" %>
<% elsif @artwork.images.attached? %>
  <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">

    <% if @artwork.images.count > 1 %>
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <% i=0 %>
        <% @artwork.images.each do %>
          <li data-bs-target="#myCarousel" data-bs-slide-to="<%= i %>" class="<%= 'active' if i == 0 %>"></li>
          <% i+=1 %>
        <% end %>
      </ol>

      <!-- Left and right controls -->
      <button class="carousel-control-prev" href="#myCarousel" role="button" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden"">Previous</span>
      </button>
      <button class="carousel-control-next" href="#myCarousel" role="button" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden"">Next</span>
      </button>
    <% end %>

    <!-- The slideshow -->
    <div class="carousel-inner">
      <% if @artwork.images %>
        <% i=0 %>
        <% @artwork.images.each do |image| %>
          <div class="carousel-item<%= ' active' if i == 0 %>" alt:"...">
            <%= image_tag image, class:"img-fluid w-100 carousel-full-width-image" %>
          </div>
          <% i+=1 %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/artworks/_index.html.erb
<% provide :background_image, asset_path('exhibition-bw.jpg') %>

<% if @artworks.any? %>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <%= render @artworks %>
  </div>
<% end %>

app/views/artworks/digital_art.html.erb
<% provide(:title, 'Digital Art') %>

<%= render 'index' %>

app/views/artworks/index.html.erb
<% provide(:title, 'Art') %>

<%= render 'index' %>

app/views/artworks/paintings.html.erb
<% provide(:title, 'Paintings') %>

<%= render 'index' %>

app/views/artworks/photography.html.erb
<% provide(:title, 'Photography') %>

<%= render 'index' %>

app/views/artworks/show.html.erb
<%= provide(:title, @artwork.listing_name ) %>
<% provide :pageheader, render('background_image') %>
<% provide :background_image, asset_path('exhibition-bw.jpg') %>

<h1><%= @artwork.listing_name %></h1>

<p class="lead"><%= @artwork.description %></p>

<% if @artwork.status == "For Sale" && !@artwork.url.nil? %>
  <%= link_to "Buy", @artwork.url, target: :_blank, class: "btn btn-light" %>
<% elsif @artwork.status == "Sold" %>
  <p class="lead">Sold</p>
<% end %>

<div class="mt-5 mb-5">
  <%= render 'image_carousel' %>
</div>

<p class="lead"><%= @artwork.medium %> <%= @artwork.year %></p>
<% if !@artwork.height.nil? && !@artwork.width.nil? %>
  <p class="lead">Width: <%= @artwork.width %> cm | Height: <%= @artwork.height %> cm</p>
<% end %>

app/views/blogposts/_background_image.html.erb
<% if @blogpost.images.attached? %>
  <%= image_tag @blogpost.images[0], class:"img-fluid w-100 full-height-image" %>
<% end %>

app/views/blogposts/_blogpost.html.erb
<div class="col">
  <div class="card bg-transparent" style="border:none">
    <% if blogpost.images.attached? %>
      <%= link_to image_tag(blogpost.images[0], class:"card-img card-img-md"), blogpost %>
    <% end %>
    <div class="card-body">
      <h5 class="card-title"><%= blogpost.post_title %></h5>
      <p class="card-text"><%= blogpost.content.to_plain_text.truncate(150) %></p>
    </div>
  </div>
</div>

app/views/blogposts/_image_carousel.html.erb
<% if @blogpost.images.attached? %>
  <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">

    <% if @blogpost.images.count > 1 %>
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <% i=0 %>
        <% @blogpost.images.each do %>
          <li data-bs-target="#myCarousel" data-bs-slide-to="<%= i %>" class="<%= 'active' if i == 0 %>"></li>
          <% i+=1 %>
        <% end %>
      </ol>

      <!-- Left and right controls -->
      <button class="carousel-control-prev" href="#myCarousel" role="button" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden"">Previous</span>
      </button>
      <button class="carousel-control-next" href="#myCarousel" role="button" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden"">Next</span>
      </button>
    <% end %>

    <!-- The slideshow -->
    <div class="carousel-inner">
      <% if @blogpost.images %>
        <% i=0 %>
        <% @blogpost.images.each do |image| %>
          <div class="carousel-item<%= ' active' if i == 0 %>" alt:"...">
            <%= image_tag image, class:"img-fluid w-100 carousel-full-width-image" %>
          </div>
          <% i+=1 %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/blogposts/index.html.erb
<% provide(:title, 'Blog') %>

<% if @blogposts.any? %>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <%= render @blogposts %>
  </div>
<% end %>

app/views/blogposts/show.html.erb
<%= provide(:title, 'Blog' ) %>
<% provide :pageheader, render('background_image') %>
<% provide :background_image, rails_blob_url(@blogpost.images[0]) %>
<h1><%= @blogpost.post_title %></h1>
<p class="lead"><%= @blogpost.created_at.strftime("%d %b %Y") %></p>
<%= @blogpost.content %>
<br>
<%= render 'image_carousel' %>

app/views/html_pages/about.html.erb
<% provide(:title, 'About') %>

<%= image_tag asset_path('portrait.jpg'), size:200, class:"rounded-circle mb-3" %>

<h1>About Lukas Hauser</h1>

<p>
  Lukas Hauser is a Swiss London-based artist who enthusiastically filled sketchbooks in his childhood until starting a finance career at 16. Apart from rare visits to his father’s art studio, he abandoned brush and canvas for more than a decade. He revived his creativity after moving to London where he became interested in street photography as a result of the vibrant and ever-changing backdrop of London and its inhabitants. Another four years later, he came across brush set, tiny paint tubes and small canvases in a Pound store, which inspired him to re-acquaint himself with his artistic nature. When the first piece was finished, his love of painting was reborn. Next to self-study, he attended two painting classes and practiced in residence.
</p>
<p>
  As the artist’s practice evolves, a style has become apparent. Deep, mysterious blacks are in strong contrast with light tones and bright colours. Next to his realistic work, he created abstract and experimental pieces. Although Hauser’s paintings consist of mixed styles and subjects, they reflect his deepest thoughts and feelings on the escape journey. He hopes to evoke similar reactions in the viewer. Lukas is also fascinated by applying machine learning to arts and trained GANs (Generative Adversarial networks) to generate art. He also minted his first NFTs.
</p>
<p>
  Lukas found showing work to the public one of the greatest experiences as an artist and photographer. However, finding the right venue and organising the exhibition was difficult, time-consuming and quite expensive. He built EXHYBYT, the AirBnb for the art world, to change that. While artists can easily find a space to exhibit their work, small businesses have the chance to generate additional revenues by renting out their empty wall spaces.
</p>

app/views/html_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<h1>Contact</h1>
<p class="lead">info@lukashauser.art</p>

app/views/html_pages/cookiepolicy.html.erb
<% provide(:title, 'Cookies') %>

<h1>Cookie Policy</h1>
<p class="lead">We don't use any cookies.</p>

app/views/html_pages/home.html.erb
<% provide(:title, 'Home') %>
<% provide :background_image, (asset_path('artist_portrait.jpg')) %>

<main class="px-3">
  <h1>Surf, Art & Rock n' Roll</h1>
  <p class="lead">Thank you for checking out Lukas Hauser's Art and Photography.</p>
  <%= link_to "Browse NFTs", digitalart_path, class: "btn btn-light" %>
</main>

app/views/html_pages/privacypolicy.html.erb
<% provide(:title, 'Privacy') %>

<h1>Privacy Policy</h1>
<p class="lead">We don't collect any data.</p>

app/views/html_pages/terms.html.erb
<% provide(:title, 'Terms') %>

<h1>Terms of Use</h1>
<p class="lead">TBC</p>

app/views/layouts/_footer.html.erb
<footer class="mt-auto">
  <div class="nav nav-masthead justify-content-center" >
    <a href="https://www.instagram.com/lukas.hauser/" target="_blank"> <i class="bi bi-instagram nav-link" style="font-size: 1.5rem; margin:5px"></i></a>
    <a href="https://facebook.com/lukashauserart" target="_blank"> <i class="bi bi-facebook nav-link" style="font-size: 1.5rem; margin:5px"></i></a>
    <a href="https://twitter.com/l_ukashauser" target="_blank"> <i class="bi bi-twitter nav-link" style="font-size: 1.5rem; margin:5px"></i></a>
    <a href="https://www.linkedin.com/in/lukashauser/" target="_blank"> <i class="bi bi-linkedin nav-link" style="font-size: 1.5rem; margin:5px"></i></a>
    <a href="https://github.com/lukas-hauser" target="_blank"> <i class="bi bi-github nav-link" style="font-size: 1.5rem; margin:5px"></i></a>
  </div>
  <nav class="nav nav-masthead justify-content-center">
    <%= link_to "About", about_path, class:"nav-link#{" active" if  current_page?(about_path) }" %>
    <%= link_to "Contact", contact_path, class:"nav-link#{" active" if  current_page?(contact_path) }" %>
    <%= link_to "Cookies", cookiepolicy_path, class:"nav-link#{" active" if  current_page?(cookiepolicy_path) }" %>
    <%= link_to "Privacy", privacypolicy_path, class:"nav-link#{" active" if  current_page?(privacypolicy_path) }" %>
    <%= link_to "Terms", terms_path, class:"nav-link#{" active" if  current_page?(terms_path) }" %>
  </nav>
  <small class="nav nav-masthead justify-content-center" style="opacity:0.5">&copy; 2016 - <%= Date.today.year %> Lukas Hauser</small>
</footer>

app/views/layouts/_navbar.html.erb
<header class="mb-auto">
  <div>
    <h3 class="float-md-start mb-0">
      <%= link_to "Lukas Hauser", root_path, class:"text-white", style:"text-decoration: none" %>
    </h3>
    <nav class="nav nav-masthead justify-content-center float-md-end">
      <%= link_to "Paintings", paintings_path, class:"nav-link#{" active" if  current_page?(paintings_path) }" %>
      <%= link_to "Photography", photography_path, class:"nav-link#{" active" if  current_page?(photography_path) }" %>
      <%= link_to "NFTs", digitalart_path, class:"nav-link#{" active" if  current_page?(digitalart_path) }" %>
      <%= link_to "Blog", blog_path, class:"nav-link#{" active" if  current_page?(blog_path) }" %>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="h-100">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex h-100 text-center text-white bg-dark">
    <div id="background" style="background-image: url(<%= background_image(yield(:background_image)) %>)">
      <div id="wrapper">
        <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
          <%= render 'layouts/navbar' %>
          <div class="mt-5 mb-5">
            <%= yield %>
          </div>
          <%= render 'layouts/footer' %>
        </div>
      </div>
    </div>
  </body>
</html>